#TODO: fix authorization
---
- name: Configure Prometheus Datasource in Grafana
  uri:
    url: "{{ data_source }}"
    method: POST
    body_format: json
    body: "{{ lookup('template', 'prometheus_datasource.json.j2') }}"
    headers:
      Content-Type: "application/json"
      Authorization: "Basic YWRtaW46YWRtaW4="
    status_code: 200
