---
#TODO get password from vault
mysql_root_password: ""

maria_db:
  - mariadb-server
  - mariadb-client


slurm:
  - slurm-wlm
  - slurm-wlm-doc
  - slurm-wlm-basic-plugins
  - slurm-wlm-torque
  - slurmdbd

nfs:
  - nfs-ganesha
  - nfs-ganesha-vfs

# can be overwritten when running the role, set to quobyte, ibm etc.
volume_type: "ceph"
volume_path: "/dev/vdb"
volume_mount_point: "/mnt/{{ volume_type }}"
