---
required_packages:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "software-properties-common"

gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_package: "docker-ce"

docker_compose_version: "v2.20.2"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ ansible_architecture }}"
docker_compose_destination: "/usr/local/bin/docker-compose"
docker_compose_mode: "u+x,g+x"
