---
vault_slurm_base_path: "secrets/data/slurm"
vault_munge_key: "munge-key-b64"

packages:
  - slurm-wlm
  - slurm-wlm-doc
  - slurm-wlm-basic-plugins
  - slurm-wlm-torque
  - nfs-common

create_slurm_directories:
  - /run/slurm
  - /var/spool/slurm/d

change_directory_ownership:
  - /var/log/slurm
  - /etc/slurm
  - /run/slurm
  - /var/spool/slurm