---
- name: Add Quobyte package key.
  ansible.builtin.apt_key:
    url: "{{ package_key }}"
    state: present

- name: Add Quobyte repository.
  ansible.builtin.apt_repository:
    repo: "{{ repo }}"
    state: present
    filename: "{{ repo_filename }}"

- name: Update apt repository.
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install Quobyte client.
  ansible.builtin.apt:
    name: quobyte-client
    state: present

- name: Upload Quobyte config file.
  ansible.builtin.template:
    src: templates/quobyte-config.j2
    dest: /etc/quobyte/client.cfg

- name: Create Quobyte mount directory.
  ansible.builtin.file:
    path: "{{ mount_path }}"
    state: directory
    recurse: true
    owner: root
    group: root

- name: Mount Quobyte volume.
  ansible.builtin.command: mount.quobyte
