---

#- include_tasks: prepare.yml

- include_tasks: install.yml

- name: Create prometheus systemd service
  template:
    src: prometheus-service.service.j2
    dest: "{{ prometheus_service_path }}"
    owner: prometheus
    group: prometheus
    mode: "0644"


- name: Copy prometheus config file
  template:
    src: prometheus.yml.j2
    dest: "{{ etc_path }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Start promethtues service.
  systemd:
    name: prometheus
    state: started
    daemon_reload: true
