---
- name: Mount NFS for compute nodes
  hosts: slurm-compute
  become: true
  tasks:
    - name: Create directory
      file:
       path: /mnt/ceph
       state: directory
       owner: ubuntu
       group: ubuntu

    - name: Mount nfs
      command: mount -a
