---
- name: Restart munge on compute nodes
  hosts: slurm-cluster
  become: true
  tasks:
    - name: Restart munge
      systemd:
        name: munge
        daemon_reload: true
        state: restarted
        
- name: Restart slurmctld
  hosts: slurm-controller
  become: true
  tasks:
    - name: Restart slurmctld
      systemd:
        name: slurmctld
        daemon_reload: true
        state: restarted

- name: Mount NFS for compute nodes
  hosts: slurm-compute
  become: true
  tasks:
    - name: Mount nfs
      command: mount -a
