---
- name: Install nfs-common package.
  apt:
    name: nfs-common
    state: present

- name: Add NFS entry
  lineinfile:
    path: /etc/fstab
    line: "{{ slurm_controller_ip }}:/mnt/ceph /mnt/ceph nfs rw,hard 0 0"
    insertafter: EOF
