---

- name: Download node-exporter {{ node_exporter_version }}
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/{{ node_exporter_artefact }}"
    force: true
  register: _download_artefact
  until: _download_artefact is succeeded
  retries: 5
  delay: 2
  check_mode: false
  when:
    - should_download

...
