---

- name: Unarchive node-exporter
  unarchive:
    src: "/tmp/{{ node_exporter_artefact }}"
    dest: /tmp
    remote_src: true

- name: Copy to destination
  copy:
    src: "/tmp/{{ node_exporter_artefact | replace('.tar.gz', '') }}/node_exporter"
    dest: "{{ node_exporter_install_dir }}/node_exporter_{{ node_exporter_version }}"
    mode: 0755
    remote_src: true

- name: Remove temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ node_exporter_artefact }}"
    - "/tmp/{{ node_exporter_artefact | replace('.tar.gz', '') }}"

...
