---

- include_tasks: prepare.yaml

- block:
    - include_tasks: download.yaml
    - include_tasks: install.yaml
    - include_tasks: configure.yaml
    - include_tasks: execute.yaml
  when: stat_node_exporter_exists.stat.exists == false
...
