---
- name: Check that the secret exists
  stat:
    path: "/home/ubuntu/{{ vault_secret_key }}"
  register: stat_result

- name: Create secret
  block:
    - name: Create secret
      shell: "{{ shell_command }}"
  when: not stat_result.stat.exists
