---
- name: Check if secret exists
  uri:
    url: "{{ vault_url }}/v1/{{ vault_base_path }}"
    method: GET
    headers: "{{ vault_headers }}"
    body_format: json
    status_code: [ 200, 204, 404 ]
  register: get_secret

- name: Create secret
  block:
    - name: Create secret
      shell: "{{ shell_command }}"
      register: secret

    - name: Convert secret to base64
      set_fact:
        secret_b64: "{{ secret.stdout | b64encode}} "

    - name: Store secret in vault
      uri:
        url: "{{ vault_url }}/v1/{{ vault_base_path }}"
        method: POST
        headers: "{{ vault_headers }}"
        body_format: json
        body: '{"data": {"{{ vault_secret_key }}": "{{ secret_b64 }}"}}'

  when: get_secret.status == 404
