---
- name: Add BeeGFS GPG key.
  apt_key:
    url: "{{ beegfs_gpg_key }}"
    state: present

- name: Add BeegFS repository.
  apt_repository:
    repo: "{{ beegfs_repository }}"
    filename: "{{ beegfs_repo_filename }}"
    state: present

- name: Update apt repositories.
  apt:
    update_cache: yes

- name: Install BeeGFS packages.
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ beegfs_server_packages }}"

- copy:
    src: '/home/ubuntu/connauthfile'
    dest: '/etc/beegfs/connauthfile'

- name: Update beegfs-meta.conf file.
  template:
    src: beegfs-meta.conf.j2
    dest: /etc/beegfs/beegfs-meta.conf
  notify: beegfs-meta

- name: Update beegfs-mgmtd.conf file.
  template:
    src: beegfs-mgmtd.conf
    dest: /etc/beegfs/beegfs-mgmtd.conf
  notify: beegfs-mgmtd
