---
required_packages:
  - autoconf
  - automake
  - build-essential
  - cryptsetup
  - libfuse-dev
  - libgpgme11-dev
  - libglib2.0-dev
  - libseccomp-dev
  - libssl-dev
  - libtool
  - pkg-config
  - runc
  - squashfs-tools
  - squashfs-tools-ng
  - uuid-dev

go_path: "$PATH:/usr/local/go/bin"

singularity_version: "4.0.1"
singularity_url: "https://github.com/sylabs/singularity/releases/download/v{{ singularity_version }}/singularity-ce-{{ singularity_version }}.tar.gz"
singularity_download_path: "/home/ubuntu/go/src/github.com/sylabs"
singularity_folder_path: "{{ singularity_download_path }}/singularity-ce-{{ singularity_version }}"

home_directory: "/home/ubuntu"
bashrc_path: "{{ home_directory }}/.bashrc"
