- name: Create ext4 filesystem
  command: "mkfs.ext4 {{ volume_path }}"

- name: Create mount point directory
  file:
    path: "{{ volume_mount_point }}"
    state: directory

- name: Mount block storage
  mount:
    path: "{{ volume_mount_point }}"
    src: "{{ volume_path }}"
    fstype: ext4
    state: mounted

