---
- name: Creates innodb directory
  file:
    path: /etc/mysql/conf.d/
    state: directory
    recurse: true

- name: Copy innodb.conf file.
  template:
    src: innodb.conf
    dest: /etc/mysql/conf.d/innodb.conf

- name: Install maria-db packages.
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ maria_db }}"

- name: Install build dependencies for mysqlclient
  become: true
  apt:
    name: [ 'pkg-config', 'libmariadb-dev' ]
    state: present

- name: Install mysqlclient
  pip:
    name: mysqlclient
    executable: pip3
    state: present

- name: Install pymssql library
  pip:
    name: pymssql
    state: present

- name: Enable and start mariadb service.
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Sets the root password
  mysql_user: user=root password="{{ mysql_root_password }}" host=localhost

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user: user="" host="{{ ansible_fqdn }}" state="absent"

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user: user="root" password="{{ mysql_root_password }}" host="::1"

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: user="root" password="{{ mysql_root_password }}" host="127.0.0.1"

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user: user="root" password="{{ mysql_root_password }}" host="localhost"

- name: Secures the MySQL root user for server_hostname domain
  mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent

- name: Setup slurm user on the database.
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: slurm
    password: slurm
    priv: "slurm_acct_db.*:ALL"

- name: Create slurm_acct_db database.
  community.mysql.mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    login_port: "3306"
    name: slurm_acct_db
    state: present
